version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - /app/node_modules
      - /app/src/config/i18n/objects
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - NODE_PATH=src/
      - REACT_APP_BASE_BACKEND_URL=http://localhost:4000
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    tty: true
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./docker-compose.yml:/app/docker-compose.yml
      - /app/node_modules
    links:
      - redis
      - mongo
    ports:
      - 4000:4000
    depends_on:
      - redis
      - mongo
    environment:
      - NODE_PATH=src/
      - BASE_FRONTEND_URL=http://localhost:3000
      - FACEBOOK_CLIENT_ID=<Your Facebook client id>
      - FACEBOOK_CLIENT_SECRET=<Your Facebook client secret>
      - GOOGLE_CLIENT_ID=<Your Google client id>
      - GOOGLE_CLIENT_SECRET=<Your Google client secret>
      - JWT_REDIS_KEY=<A random string>
      - JWT_SECRET=<A random string>
      - MONGODB_URI=mongodb://mongo/boilerplate-dev
      - NODE_ENV=development
      - PASSWORD_PEPPER=<A random string>
      - PORT=4000
      - REDIS_URI=redis://redis:6379
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6543:6543
volumes:
  mongodata:
