version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
      - /app/src/config/i18n
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_BACKEND_URL=http://localhost:4000
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./docker-compose.yml:/app/docker-compose.yml
      - /app/node_modules
    links:
      - redis
      - mongo
    ports:
      - 4000:4000
    depends_on:
      - redis
      - mongo
    environment:
      - BASE_FRONTEND_URL=http://localhost:3000
      - FACEBOOK_CLIENT_ID=857754284683597
      - FACEBOOK_CLIENT_SECRET=a47cd72988e56dfd94ba6c1810f9c05a
      - GOOGLE_CLIENT_ID=222445472327-dl0o4j0vfdg9r7bg99kkd0vimmoi3je0.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=PYh3Wx7K8E9igJcWF5IVMeXB
      - JWT_KEY=jwtKey
      - JWT_SECRET=jwtSecret
      - MONGODB_URI=mongodb://mongo/charter-dev
      - NODE_ENV=development
      - PASSWORD_PEPPER=passwordPepper
      - PORT=4000
      - REDIS_URI=redis://redis:6379
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6543:6543
volumes:
  mongodata:
